### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by roudikk** [JustZak/DilatingDotsProgressBar#8]
Hello, it is working on a signed minifyEnabled true apk, however the dots are not dilating.

I tried : 
-keep class com.github.justzak.dilatingdotsprogressbar.**{ *; }
in proguardrules

**Comment by dharmita1990** [comment]
I included it's different java classes and for proguard enabled ,i wrote 
-keep class packagename.DilatingDotDrawable { *; }
and its working.

**Comment by rahulchowdhury** [comment]
As @dharmita1990 suggested, adding the following line did the job,

`-keep class com.zl.reik.dilatingdotsprogressbar.DilatingDotDrawable { *; }`

**Comment by jp1017** [comment]
> -keep class com.zl.reik.dilatingdotsprogressbar.DilatingDotDrawable { *; }

This worked for me. :smile: :+1: Thanks. @rahulchowdhury
